### PR TITLE
Fuse tabs for Exp and Recommendations

### PR DESCRIPTION
**Pull request by bhanvimenghani**
This pr contains changes suggested for Fuse tabs functionality ,

- merges the 2 Tabs exp and recommendations
- fixes the Recommendations button, refresh icon 
- and other minor issues faced while integration.

https://www.loom.com/share/42259f859be9499a96713128bcfd8fb9?sid=95ca3ed9-8893-41f4-a019-c60c25b3d984

### CODE REVIEW

**Comment by bhanvimenghani** [comment]
Image: quay.io/bmenghan/p183

**Comment by kusumachalasani** [comment]
Can you include some notifications when you click on `Generate Recommendations` saying - "Recommendations are generated for experiment : experiment_name".

**Comment by bhanvimenghani** [comment]
Notifications will be a part of the subsequent prs as the fuse of the tabs is required to be done before the logic & placement of notifications is finalized. Also im only planning to display the notifications already coming from the api, will it be fine if i try to add some notification from my end?

**Comment by kusumachalasani** [comment]
> Notifications will be a part of the subsequent prs as the fuse of the tabs is required to be done before the logic & placement of notifications is finalized. Also im only planning to display the notifications already coming from the api, will it be fine if i try to add some notification from my end?

Yes, this is only to let users know that at the backend it is trying to generate the  Recommendations for that experiment. As a user on clicking refresh button, I don't see any changes. Will be helpful to notify, that it is trying to generate recommendations at the backend!

**Comment by bhanvimenghani** [comment]
https://www.loom.com/share/412fba473ef8468198dca7a99d986b5b?sid=c76b4e4c-182a-42f1-8730-e21a713bfd86

**Comment by kusumachalasani** [comment]
@bhanvimenghani Can you please share the latest image ?

**Comment by bhanvimenghani** [comment]
quay.io/bmenghan/update-pr183

**Comment by kusumachalasani** [comment]
While selecting the experiments itself it shows `Generating Recommendations` notification. It is supposed to show only when we click 'Generate Recommendations` and not while selecting the experiment. 
Also, I see the notification `Unable to Generate Recommendations` even when I'm selecting a different experiment. When we try to select a new experiment - the previous notifications should not be seen.

image

**Comment by bhanvimenghani** [comment]
on the click of referesh icon only u want me to show the notification? not on calling the list recc

**Review by dinogun — APPROVED** [review]
LGTM

**Pull request merged**
