### PR TITLE
Replaces Generate API call to List API call

### PR DESCRIPTION
**Pull request by bhanvimenghani**
This pr replaces generate recc api call with list recc api call
solves jira 276. This is built on top of PR 180, and needs 180 to be merged before this one.

### CODE REVIEW

**Review by kusumachalasani — COMMENTED** [review]
I see it has the changed related to PR#180.  Requires a rebase before merging. 
As part of the changes related to this PR - LGTM!

**Comment by bhanvimenghani** [comment]
I think i need to remove this "adds experiment type" commit as well, right it comes from the 180 pr which is merged. so that just the changes in this one r visible

**Review by kusumachalasani — APPROVED** [review]
LGTM!

**Comment by bhanvimenghani** [comment]
@chandrams can u merge this pr

**Review by chandrams — APPROVED** [review]
LGTM!

**Comment by dinogun** [comment]
@kusumachalasani @chandrams Please note that this PR was against `main` and not `mvp_demo`. We should always merge into `main` only after merging into `mvp_demo` and completing testing.

**Pull request merged**
