### PR TITLE
Fixes type error

### PR DESCRIPTION
**Pull request by bhanvimenghani**
Fixes all possibilities causing _`_TypeError: Cannot read properties of undefined (reading 'amount')_`_ UI works fine after this change, displaying empty values instead of throwing empty ui page.

### CODE REVIEW

**Comment by chandrams** [comment]
@bhanvimenghani - Do you have a docker image with this fix?

**Comment by bhanvimenghani** [comment]
@chandrams  `quay.io/bmenghan/pr190` created this img with changes

**Review by chandrams — APPROVED** [review]
LGTM

**Comment by chandrams** [comment]
@kusumachalasani - Can you please review this PR

**Review by kusumachalasani — APPROVED** [review]
LGTM!

**Pull request merged**
