### PR TITLE
Box Plots - Part 2

### PR DESCRIPTION
**Pull request by bhanvimenghani**
This pr is built on top of 185, Contains advance changes for box plots 
1. Limits , request lines for all 4 graphs
2. Axis values
3. Cost perf tabs graphs

### CODE REVIEW

**Comment by bhanvimenghani** [comment]
quay.io/bmenghan/pr186

**Comment by dinogun** [comment]
@bhanvimenghani Please fix the conflicts

**Comment by bhanvimenghani** [comment]
@dinogun fixed conflicts

**Review by dinogun — APPROVED** [review]
Merging to get a demo image

**Pull request merged**
