### PR TITLE
Adds 2 tabs on the side Datasource and experiment

### PR DESCRIPTION
**Pull request by bhanvimenghani**
[link ](https://www.loom.com/share/4b98b79d452943f5bcb10fe5c0cf4f70?sid=b42e9574-7056-4711-8fb5-f05c6807fd99) This is a video link of how the ui looks after changes made in this pr.
Solves jira 279

### CODE REVIEW

**Comment by kusumachalasani** [comment]
@bhanvimenghani Can you please share the image which has this change ?

**Comment by bhanvimenghani** [comment]
quay.io/bmenghan/two-tabs-side

**Comment by kusumachalasani** [comment]
@bhanvimenghani I'm assuming this doesn't include going back to 'Experiments' tab after we click 'Create Experiment'. Is that right ?

**Comment by kusumachalasani** [comment]
Few observations while testing:
- While clicking '+'  to create the experiment, I see 'Experiment' tab first and then the CreateExperiment page.
-  Alert related to  'Experiment created sucessfully' disappears fast.
- After 'Create Experiment' is complete - it is still at the same page with 'Create Experiment' button still in enable state. After completion, it should go to 'Experiments' tab by default.

**Review by kusumachalasani — APPROVED** [review]
Approving, as the changes required per the comments can be addressed in the another PR.

**Comment by bhanvimenghani** [comment]
> * While clicking '+'  to create the experiment, I see 'Experiment' tab first and then the CreateExperiment page.
> * Alert related to  'Experiment created sucessfully' disappears fast.
> * After 'Create Experiment' is complete - it is still at the same page with 'Create Experiment' button still in enable state. After completion, it should go to 'Experiments' tab by default.

Added these Observations in the Kruize UI Todo list!

**Review by dinogun — APPROVED** [review]
LGTM

**Pull request merged**
