### PR TITLE
Displays GPU Reccommendations 

### PR DESCRIPTION
**Pull request by bhanvimenghani**
This pr is built on top of Box plot prs 185 and 186 and contains changes to add gpu recommendations in the cost and perf config

### CODE REVIEW

**Comment by bhanvimenghani** [comment]
GPU recommendation json used for development
[Uploading recommendation,json.json…]()

**Comment by bhanvimenghani** [comment]
quay.io/bmenghan/pr187

**Comment by dinogun** [comment]
@bhanvimenghani Please fix the conflicts

**Comment by bhanvimenghani** [comment]
@dinogun fixed conflicts

**Review by dinogun — APPROVED** [review]
Merging to create demo build

**Pull request merged**
